### ISSUE TITLE
Use separate workflows with filter patterns to avoid pushing code that hasn't changed

### ISSUE THREAD

**Issue by nateraw** [nateraw/my-huggingface-repos#1]
We should use separate workflow files containing `path` filter patterns to avoid pushing code that hasn't changed.

For example, for a space named `some_space`...

```
on:
  push:
    paths:
      - spaces/some_space/**
```
